language: node_js
addons:
  apt:
    update: true

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- -version 1.16.0
  - export PATH=$HOME/.yarn/bin:$PATH

node_js:
  - 'lts/*'
  # Disabled until https://github.com/facebook/jest/issues/8069 is resolved
  #- "node"

cache:
  directories:
    - node_modules
    - ~/.yarn
