name: Node CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x, 14.x]

    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - run: yarn version check
        if: "github.actor != 'dependabot[bot]' && !contains(github.ref , 'release/') && !contains(github.head_ref , 'release/')"
        name: Version Check

      - run: yarn install
        name: Install Dependencies

      - run: yarn ci
        name: Execute Tests
        env:
          CI: true

      - name: Publish coverage to codecov.io
        uses: codecov/codecov-action@v1.0.13
        if: success() && matrix.node-version == '14.x'
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  # This is a separate step to allow for the full matrix build to complete
  auto-merge:
    name: Auto-Merge Dependabot PRs
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: check actor
        run: echo "actor is $GITHUB_ACTOR"

      - name: auto-merge
        # Because the fix-dependabot.yml worfklow uses my own PAT to patch dependabot updates
        if: (github.actor == 'dependabot[bot]' || github.actor == 'darthtrevino') && contains(github.ref, 'dependabot/npm_and_yarn')
        uses: ridedott/merge-me-action@v1
        with:
          # This must be used as GitHub Actions token does not support
          # pushing to protected branches.
          GITHUB_LOGIN: darthtrevino
          GITHUB_TOKEN: ${{ secrets.AUTOMERGE_PAT }}
